### PR TITLE
Added ability to provide custom context

### PR DESCRIPTION
**Pull request by jaxoncreed**
WARNING: DO NOT MERGE

This doesn't work but I wanted to open the pull request for discussion.

I'd like to use the functionality for auth from this library, but provide my own context so that I can use attributes that aren't currently in the context file.

This doesn't work because the default export is a Proxy and will supersede any attributes for non-default exports.

@RubenVerborgh Is this a feature that seems apt?

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Good feature indeed (see https://github.com/solid/query-ldflex/issues/1).

Need to think about the right implementation.

In parallel, do you have suggestions to extend the default context for auth?

**Comment by jaxoncreed** [comment]
I'll need to get back to you on the auth stuff. I'll keep a note of useful predicates as I'm building it.

Outside of auth, I noticed that there were quite a few ldp related predicates that weren't in the default context like `ldp:contains`

As for the implementation of this feature. I'd very much like to be able to just bring in another export as a function and pass it a context, like I've done in this pull request. I'm not as familiar with JS Proxies as you are, but it looks like that isn't possible if a Proxy is the default export. You could also change it so that it's not a default export, but there seems to be quite a few libraries that are already dependent on that, so I'm not sure if we want to go through the headache of an interface change.

**Comment by RubenVerborgh** [comment]
> I'd very much like to be able to just bring in another export as a function and pass it a context

Yes, doing something like that conceptually is likely the best way. We want to avoid messing with the default instance.

Instead of an export, it will probably be a method on the proxy, or an export on another module (such as `@solid/query-ldflex/custom`).

**Comment by jaxoncreed** [comment]
Ah perfect. Good ideas. I'll go ahead and work on doing that.

**Comment by RubenVerborgh** [comment]
Thanks, but warning: since this is the main export, I'll be very opinionated on its implementation 😛

Let's think about a good function name. Something like `solid.data.customize({ context: … })` perhaps?
I also think we should cover two cases: replacing the context, and adding to the existing context. The latter in theory is just a matter of passing in `{ ...solid.data.context, mything: {} }`, but might be useful to have a shortcut. Or maybe not, as it's already quite simple.

**Comment by rubensworks** [comment]
> The latter in theory is just a matter of passing in { ...solid.data.context, mything: {} }, but might be useful to have a shortcut.

Note that this won't work when the context is an array (of contexts) or a string (e.g. https://schema.org/). So I would definitely add a shortcut for this, which could be implemented by [passing `parentContext` to the JSON-LD context parser](https://github.com/rubensworks/jsonld-context-parser.js/blob/master/lib/ContextParser.ts#L379-L380).

**Comment by RubenVerborgh** [comment]
> Note that this won't work when the context is an array (of contexts) or a string

And @rubensworks saves the day once more. Noted!

So then I propose `{ context: … }` and `{ extendContext: … }`.
Or maybe even `{ parentContext: true }` for keeping what is there, and `{ parentContext: string }` for the regular mechanism.

BTW https://twitter.com/RubenVerborgh/status/1120333659712696322

**Comment by jaxoncreed** [comment]
Good news is, I learned a lot about the quirks of Proxies while trying to figure this out. Bad news is, I can't do the 100% optimal interface I wanted.

```
export default rootPath = withCustomContext(defaultContext);

export function withCustomContext(customContext) {
  return new PathFactory({
    // Handlers of specific named properties
    handlers: {
      ...defaultHandlers,

      // The `from` property takes a source URI as input
      from: new SourcePathHandler(getSubjectPathFactory(customContext)),
      // The `user` property starts a path with the current user as subject
      user: new UserPathHandler(getSubjectPathFactory(customContext)),

      // Clears the cache for the given document (or everything, if undefined)
      clearCache: ({ settings }) => doc => settings.queryEngine.clearCache(doc),

      // Expose the JSON-LD context
      context: () => customContext,

      customize: () => async ({ context, parentContext = defaultContext }) => {
        const parsePromises = [contextParser.parse(context)];
        if (parentContext)
          parsePromises.push(contextParser.parse(parentContext));
        const contexts = await Promise.all(parsePromises);
        let combinedContexts;
        if (contexts.length > 1)
          combinedContexts = { ...contexts[0], ...contexts[1] };
        else
          combinedContexts = contexts[0];
        return withCustomContext({ '@context': combinedContexts });
      },
    },
    // Handlers of all remaining properties
    resolvers: [
      // `data[url]` starts a path with the property as subject
      new SubjectPathResolver(getSubjectPathFactory(customContext)),
    ],
    // Global query engine (currently only used for clearing the cache)
    queryEngine: new ComunicaUpdateEngine(),
  }).create();
}
```

I took your advice and created a `customize` handler which takes in a `context` and a `parentContext`. It then used @rubensworks 's jsonld-parser to parse the contexts and combine them. The problem lies in the fact that parsing is asynchronous. Because the `customize` handler returns a Promise and the result of that Promise (the PathProxy) is thenable, the PathProxy will execute it's asynchronous call. This is obviously not something we want and I have two possible solutions that I'd like your feedback on:

1. Structure the Proxy is such a way that the asynchronous call to the parser is just the first stage of async calls that need to be executed when the time comes. This is sub-optimal as it would require running the parser whenever you want to await ldflex.
2. Just say that the `customize` handler can only accept a context object as JSON and let the user use the parser before calling the `customize` method.

**Comment by RubenVerborgh** [comment]
Path resolving is already async, so we can use a promise to the context.
However, that code is in LDflex itself, not in Solid.

Thanks for your work on this; will follow up ASAP.

**Comment by jaxoncreed** [comment]
@RubenVerborgh are there any updates on this? I could open a feature request for ld-flex, or I could do some work on it myself, but I'm not 100% sure what the proper way to do it is.

**Comment by RubenVerborgh** [comment]
ASAP 🙂 busy week

**Comment by RubenVerborgh** [comment]
@jaxoncreed After some (apparently very long) thought, I have implemented it as follows: https://github.com/solid/query-ldflex/tree/v2.6.0#adding-a-custom-json-ld-context (through 91c4a409c2431d66c92fbdc04ab2756201383a74). Thanks for your help and thinking work here!

**Pull request closed without merging**
