### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by angelo-v**
Just ran `npm audit fix` to fix vulnerabilities

### CODE REVIEW

**Comment by angelo-v** [comment]
The build error is weird. I can reproduce it with node v13.13.0 on my local machine, but it also fails on master with that node version. With v13.12.0 both master and my PR are building without problem.

**Comment by RubenVerborgh** [comment]
Thanks. It's likely a 13-specific error that will resolve itself over time.

Shall we maybe for simplicity close this one? I always update the packages anyway before a version bump, and package-lock.json only affects dev, not production.

**Comment by angelo-v** [comment]
Hmm, I usually do it the other way arround, to not start developing new stuff based on outdated versions. If something breaks like here I would have suspected my changes to be the cause. But it's fine for me if you prefer otherwise

**Comment by RubenVerborgh** [comment]
Is these changes indeed, but indirectly; some other package broke in an in-range update. I assume they will fix, given that it’s Babel.

**Comment by RubenVerborgh** [comment]
The package in question was fixed; did a full lockfile update in c8e8362f3b797e794336c631a0c1937d91206918.

**Pull request closed without merging**
